### ISSUE TITLE
Gör detta repository privat

### ISSUE THREAD

**Issue by emilhem** [Nickedude/DAT326#1]
Genom att ha detta repository publikt delar du med dig av din lösning. Detta medför att du och dina labbkamrater kan råka illa ut.

Du kan skapa ett repository på Chalmers om du inte vill ha GitHub private.

Skapa en mapp i `/chalmers/users/[CID]/` förslagsvis med namnet `GIT`. I mappen skapar du en till mapp som du döper till `DAT326`. I mappen `DAT326` skapar du ett tomt repository genom att köra `git --bare`.

På din lokala dator kan du sedan gå till din `DAT326` och skriva `git remote set-url origin ssh://[CID]@remote11.chalmers.se/chalmers/users/[CID]/GIT/DAT326/`

Om du senare vill klona repository:t på en Chalmers-dator så kan du skriva `git clone ~/GIT/DAT326/`.

Kör en `git push origin master` efteråt. Nu har du satt upp ett git repository på Chalmers servrar som är privat! *virtual high five*

**Comment by Nickedude** [comment]
Woops, hade helt glömt av att göra det private. Ordnar det direkt. :+1: 
*virtual high five*
